### ISSUE TITLE
ROS2支持

### ISSUE THREAD

**Issue by YongLD** [RocShi/rostaller#3]
Ros2是否也支持？

**Comment by RocShi** [comment]
hello @YongLD ，

目前 rostaller 仅支持 ROS 1，后续可能添加对 ROS 2 的支持，敬请期待。

**Comment by RocShi** [comment]
@YongLD 

Hi，rostaller 已更新至 v0.7 版本，添加对 Ubuntu 20.04 + ROS 2 Galactic 的支持。

欢迎使用 🙂

**Comment by RocShi** [comment]
@YongLD 

Hi，rostaller 已更新至 v0.7 版本，添加对 Ubuntu 20.04 + ROS 2 Galactic 的支持。

欢迎使用 🙂
