### ISSUE TITLE
关于工具的使用问题

### ISSUE THREAD

**Issue by nishenge** [RocShi/rostaller#4]
您好，我在使用最后一个命令的时候出现如下提示，不知道怎么回事

cp: 无法获取'SimpleSources/sources.list' 的文件状态(stat): 没有那个文件或目录

**Comment by RocShi** [comment]
@nishenge 

你好，现在 v0.5 版本中的 sources.list 文件是和 Ubuntu 版本有关的，应该不会报你说的这种错误，你是直接 clone 下来然后运行的吗？方便地话可进一步提供更详细的信息（如 log 文件、报错截图等）我看下。

**Comment by nishenge** [comment]
> @nishenge
> 
> 你好，现在 v0.5 版本中的 sources.list 文件是和 Ubuntu 版本有关的，应该不会报你说的这种错误，你是直接 clone 下来然后运行的吗？方便地话可进一步提供更详细的信息（如 log 文件、报错截图等）我看下。

您好  我做了一个演示视频  您可以看一下 https://smartshen.lanzoui.com/iEjwbuseyab  解压后就能看

因为没办法在线clone 所以我是下载下来放在那个目录下的

**Comment by RocShi** [comment]
@nishenge 

hello，要进到 rostaller 仓库里面为 run.sh 添加可执行权限，然后运行 run.sh，你的操作方式因为相对路径不对所以会导致找不到文件。README 里没有写进入仓库这一步。

**Comment by nishenge** [comment]
> @nishenge
> 
> hello，要进到 rostaller 仓库里面为 run.sh 添加可执行权限，然后运行 run.sh，你的操作方式因为相对路径不对所以会导致找不到文件。README 里没有写进入仓库这一步。

Hello，我对Linux不是很熟悉，麻烦您看一下是不是这样操作的。   结果依旧是没通过。   如果方便的话，麻烦您告诉我具体的操作步骤。   谢谢        

这是我的操作视频  https://smartshen.lanzoui.com/iQZsnuswt1a

**Comment by RocShi** [comment]
@nishenge
hello，你的操作没有问题，视频二中的错误是出在了 curl 向 http://keyserver.ubuntu.com 发起请求时连接失败，应该是网络问题（比如防火墙配置），你可以看下浏览器中是否可以直接打开 http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 ，也可以试下直接在终端中执行下面语句看是否有效：

```bash
curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add -
```

如果没有问题得话，重新运行 run.sh。

**Comment by nishenge** [comment]
> @nishenge hello，你的操作没有问题，视频二中的错误是出在了 curl 向 http://keyserver.ubuntu.com 发起请求时连接失败，应该是网络问题（比如防火墙配置），你可以看下浏览器中是否可以直接打开 http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 ，也可以试下直接在终端中执行下面语句看是否有效：
> 
> ```shell
> curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add -
> ```
> 
> 如果没有问题得话，重新运行 run.sh。

hello，非常感谢您的耐心解答，已成功解决问题。    谢谢您

**Comment by nishenge** [comment]
如果可以的话  希望您更新了Ubuntu14安装ros

**Comment by RocShi** [comment]
> > @nishenge hello，你的操作没有问题，视频二中的错误是出在了 curl 向 http://keyserver.ubuntu.com 发起请求时连接失败，应该是网络问题（比如防火墙配置），你可以看下浏览器中是否可以直接打开 http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 ，也可以试下直接在终端中执行下面语句看是否有效：
> > ```shell
> > curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | sudo apt-key add -
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果没有问题得话，重新运行 run.sh。
> 
> hello，非常感谢您的耐心解答，已成功解决问题。 谢谢您 （我的解决办法是使用了科学上网）

应该不需要科学上网的，保证正常的网络连接即可，如果要求科学上网，那么这个工具就没有意义了。

---

> 如果可以的话 希望您更新了Ubuntu14安装ros

请单独再开一个 issue 吧，这个 issue 我先关闭掉了 🙂

**Comment by RocShi** [comment]
@nishenge 

hello，已添加对 Ubuntu 14.04 自动安装 ROS 1 Indigo 的特性，已通过测试，欢迎试用 🙂
