### ISSUE TITLE
最新rostaller版本安装过程中存在的问题（可能是BUG）

### ISSUE THREAD

**Issue by knightdby** [RocShi/rostaller#6]
安装环境：Ubuntu20.04
存在的问题：
最新rostaller版本安装ROS1，会出现找不到rosdistro-master文件夹下文件的情况，需要将rosdistro-master文件夹下的文件移动到上一级文件夹中，即可解决上述问题。此外，安装完成需要重新配置环境变量：`echo "source /opt/ros/melodic/setup.bash" >>~/.bashrc
source ~/.bashrc`。

**Comment by RocShi** [comment]
hello @knightdby ,

1、“文件找不到”：v0.7.2 释放前进行了所有支持平台的测试，不大可能出现该问题，我稍后复测下，方便地话可以贴下你的执行过程及报错信息；

2、“需要重新配置环境变量”：自 v0.7 起，rostaller 增加了对 ROS 2 的支持，所以取消了 ROS 环境变量的自动写入，因为 Ubuntu 20.04 下可能出现 ROS 1 / ROS 2 共存使用的情况。

谢谢关注~

**Comment by knightdby** [comment]
感谢您的回复！
1.“文件找不到”问题：
我按照readme的步骤进行执行安装：
`git clone https://github.com/RocShi/rostaller.git
cd rostaller
chmod +x ./run.sh
./run.sh`
报错信息如下：
![8vL60XxpTX](https://user-images.githubusercontent.com/75298418/162850837-75b33158-2685-447b-a85c-2141ffa6892b.png)
出现问题后，发现了正式版本v0.7.2，尝试重新下载正式发布版本进行安装，安装过程中报错信息：
![7pRCnthoO6](https://user-images.githubusercontent.com/75298418/162850863-4aa390d7-6810-41c9-9178-3733cd5b2e10.png)
2.“重新配置环境变量”：版本更新内容建议在readme中进行说明，初学者可能还没有想到环境变量的问题，怀疑是安装问题。
最后，谢谢您的对rostaller的维护和更新，真是一个了不起的项目，能够让大家非常方便快捷地开始ROS编程，后面期待能够一键配置深度学习环境。

**Comment by RocShi** [comment]
hello @knightdby ,

1、“文件找不到”：我使用了新的 Ubuntu 20.04.2 虚拟机进行了测试，没有复现你所说的问题，从报错信息来看，猜测问题出在你的机器上的 `/usr/lib/python3/dist-packages/rosdep2/rep3.py` 文件和 `usr/lib/python3/dist-packages/rosdistro/__init__.py` 文件已经在什么时候被更改过了，且没有恢复，导致执行 rostaller 时 `rosdep update` 步骤报错。你可以分别执行下述两条命令看下输出：

```bash
# expect output: REP3_TARGETS_URL = 'https://raw.githubusercontent.com/ros/rosdistro/master/releases/targets.yaml'
sudo cat /usr/lib/python3/dist-packages/rosdep2/rep3.py | grep targets.yaml
```

```bash
# expect output: DEFAULT_INDEX_URL = 'https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml'
sudo cat /usr/lib/python3/dist-packages/rosdistro/__init__.py | grep index-v4
```

估计你得到的结果能和报错信息对应上，分别把这两个 Python 脚本改回原样即可：

```bash
sudo sed -i '/targets.yaml/c\REP3_TARGETS_URL = 'https://raw.githubusercontent.com/ros/rosdistro/master/releases/targets.yaml'' /usr/lib/python3/dist-packages/rosdep2/rep3.py
```

```bash
sudo sed -i '/index-v4/c\DEFAULT_INDEX_URL = 'https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml'' /usr/lib/python3/dist-packages/rosdistro/__init__.py
```

后续再运行 rostaller 应该就正常了。

2、“需要重新配置环境变量”：多谢建议，下个版本会改进；

3、“一键配置深度学习环境”：后续我遇到相应需求可能会 open 一个新的 github project，敬请期待。

😄
